name: Tournaments
main: Main
version: 0.0.2
commands:
   getstate:
      description: Shows current game state.
      usage: /<command>
   getplayercount:
      description: Shows current player count.
      usage: /<command>
   start:
      description: Starts the game.
      usage: /<command>
   currentqueue:
      description: Shows current waiting players.
      usage: /<command>
   end:
      description: End a running game.
      usage: /<command>